name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: --health-cmd="pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1']
        moodle-branch: ['MOODLE_401_STABLE', 'MOODLE_402_STABLE', 'master']
        database: ['mariadb', 'pgsql']
        include:
          - php: '8.2'
            moodle-branch: 'MOODLE_402_STABLE'
            database: 'pgsql'

    name: ${{ matrix.moodle-branch }}  php ${{ matrix.php }}  ${{ matrix.database }}

    steps:
      - name: checkout plugin
        uses: actions/checkout@v3
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: pcov

      - name: add plugin
        uses: actions/checkout@v3
        with:
          repository: catalyst/moodle-local_aws
          path: extras/local_aws

      - name: npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ matrix.php }}-${{ matrix.moodle-branch }}-${{ matrix.database }}-cache
          restore-keys: |
            node-${{ matrix.php }}-${{ matrix.moodle-branch }}-${{ matrix.database }}-cache

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8

      - name: install Moodle
        run: moodle-plugin-ci install --db-host=127.0.0.1 --plugin this-plugin --extra-plugins=extras
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: fix aws sdk
        run: sed -i 's/. Client::VERSION/ /g' functions.php
        working-directory: moodle/local/aws/sdk/GuzzleHttp

      - name: phplint
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phplint

      - name: phpcpd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpcpd

      - name: phpmd
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi savepoints

      - name: grunt
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi grunt || true

      - name: mustache
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi mustache

      - name: phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text --coverage-clover

      - name: coveralls
        if: ${{ always() }}
        run: moodle-plugin-ci coveralls-upload
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: behat
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --profile=chrome

      - name: classic
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi behat --suite="classic" --profile=chrome

      - name: AWS engine
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text moodle/admin/tool/translate/engine/aws

      - name: Google engine
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text moodle/admin/tool/translate/engine/google

      - name: Deepl engine
        if: ${{ always() }}
        run: moodle-plugin-ci --ansi phpunit --coverage-text moodle/admin/tool/translate/engine/deepl
